---
- name: A simple task we can use to test webhooks in github
  connection: ansible.builtin.local
  hosts: localhost
  
  tasks:
  - ansible.builtin.debug:
      msg: "Hello Webhook World! Instant real-time updates on the way!!"
