---
- name: A simple task we can use to test webhooks in github
  connection: ansible.builtin.local
  hosts: localhost
  
  tasks:
  - ansible.builtin.debug:
      msg: "Github webhook from rzfeeser/aap-webhook! Instant real-time updates are GO!"

  - ansible.builtin.debug:
      msg: "Follow Professor Feeser on Youtube via youtube.com/@CodeWithFeeser"
